# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
        environment:
          GEOCODER_USERNAME: SA
          GEOCODER_PASSWORD: yourStrong(!)Password
          GEOCODER_HOST: localhost
          GEOCODER_PORT: 1433
          GEOCODER_DBNAME: geocoder

      - image: microsoft/mssql-server-linux:2017-CU3
        environment:
          ACCEPT_EULA: Y
          SA_PASSWORD: yourStrong(!)Password

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install packages
          command: |
            sudo apt-get update
            sudo apt-get install -y apt-transport-https unixodbc unixodbc-dev
            sudo apt-get --assume-yes install freetds-dev freetds-bin

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -e .

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pylint src tests
            mypy --ignore-missing-imports src tests
            pytest tests

      - store_artifacts:
          path: test-reports
          destination: test-reports
